HealthDisease/HealthDisease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from healthapp.views import *
# from .api import router

urlpatterns = [
    # path('api/sensoviz/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path('patient_home', User_Home,name="patient_home"),
    path('doctor_home', Doctor_Home,name="doctor_home"),
    path('admin_home', Admin_Home,name="admin_home"),
    path('about', About,name="about"),
    path('contact', Contact,name="contact"),
    path('gallery', Gallery,name="gallery"),
    path('login', Login_User,name="login"),
    path('login_admin', Login_admin,name="login_admin"),
    path('signup', Signup_User,name="signup"),
    path('logout', Logout,name="logout"),
    path('change_password', Change_Password,name="change_password"),
    # path('prdict_heart_disease', prdict_heart_disease,name="prdict_heart_disease"),
    path('add_heartdetail', add_heartdetail,name="add_heartdetail"),
    path('view_search_pat', view_search_pat,name="view_search_pat"),

    path('view_doctor', View_Doctor,name="view_doctor"),
    path('add_doctor', add_doctor,name="add_doctor"),
    path('change_doctor/<int:pid>/', add_doctor,name="change_doctor"),
    path('view_patient', View_Patient,name="view_patient"),
    path('view_feedback', View_Feedback,name="view_feedback"),
    path('edit_profile', Edit_My_deatail,name="edit_profile"),
    path('profile_doctor', View_My_Detail,name="profile_doctor"),
    path('sent_feedback', sent_feedback,name="sent_feedback"),

    path('delete_searched/<int:pid>', delete_searched, name="delete_searched"),
    path('delete_doctor<int:pid>', delete_doctor, name="delete_doctor"),
    path('assign_status<int:pid>', assign_status, name="assign_status"),
    path('delete_patient<int:pid>', delete_patient, name="delete_patient"),
    path('delete_feedback<int:pid>', delete_feedback, name="delete_feedback"),
    path('predict_desease/<str:pred>/<str:accuracy>/', predict_desease, name="predict_desease"),

    path('add_genralhealth', add_genralhealth, name="add_genralhealth"),

    path('search_blood', search_blood, name="search_blood"),
    path('donate_blood', donate_blood, name="donate_blood"),

    path('request_blood', request_blood, name="request_blood"),
    path('donator_blood', donator_blood, name="donator_blood"),

    path('change_status/<int:pid>/', change_status, name="change_status")

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthDisease/healthapp/models.py
from operator import mod
from pyexpat import model
from re import M
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
DOCTOR_STATUS = ((1, 'Authorize'), (2, 'UnAuthorize'))

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.IntegerField(DOCTOR_STATUS, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    contact = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    doj = models.DateField(null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Admin_Helath_CSV(models.Model):
    name = models.CharField(max_length=100, null=True)
    csv_file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

class Search_Data(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    prediction_accuracy = models.CharField(max_length=100,null=True,blank=True)
    result = models.CharField(max_length=100,null=True,blank=True)
    values_list = models.CharField(max_length=100,null=True,blank=True)
    predict_for = models.CharField(max_length=100,null=True,blank=True)
    created = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.patient.user.username

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    messages = models.TextField(null=True)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.user.username

class GeneralHealthProblem(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Blood_Donation(models.Model):
    status = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    blood_group = models.CharField(max_length=100, null=True, blank=True)
    place = models.CharField(max_length=100, null=True, blank=True)
    purpose = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now=True,null=True)
    active = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self):
        return self.user.user.username

HealthDisease/healthapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ('status', 'user', 'dob', 'doj')

HealthDisease/healthapp/templates/add_genralhealth.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->



	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			{% if predictiondata %}

			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Result After Prediction</h3>
			</div><hr/>

			<div class="form-group row">
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Model Name</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px;background:blue;color:white">
					<label><b>Prediction Output</b></label>
				</div>
				{% for i, j in predictiondata.items %}
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label><b>{{i}}</b></label>
				</div>
				<div class="col-md-6" style="border:1px solid black;padding:6px">
					<label>{{j}}</label>
				</div>
				{% endfor %}
			
			</div>

			{% else %}



			
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Select Your Problem</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">

						{% for i in alldisease %}
						<div class="col-md-3" style="border:1px solid black;padding:6px">
							<label>{{i}}</label>
							<input type="radio" name="{{i}}" style="width:30px;height:15px">
						</div>
						{% endfor %}
					
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Send Data</button>
				</form>
			</div>
			{% endif %}
		</div>
	</section>
	<!-- //register -->

{% endblock %}

HealthDisease/healthapp/templates/assign_status.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<style>
    fieldset{
    color:black;
    }
</style>
<div class="container" style="margin-top:5%;margin-bottom:5%">
    <div class="row">
        <div  class="col-md-12">
                <h2 style="margin-top:5%;background:#262626;padding:19px;color:white">ASSIGN STATUS
                </h2>
<form id="loginForm" action="#" method="post" style="width:100%" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset id="body">
        <div class="row">
          <div class="col-md-12">
                <fieldset>
                    <label for="email" style="color:black;">Username</label><br>
                    <input style="height:33px;width:100%" type="text" name="uname" id="email" value="{{prod.user.username}}" style="height:33px;" readonly>
                </fieldset>
          </div>
          <div class="col-md-12">
                <fieldset>
                    <label for="email" style="color:black;">Status</label>
                    <select name="stat" class="form-group" style="height:33px;width:100%">
                        <option>----Select Status----</option>
                        <option value="Accept">Accept</option>
                        <option value="Reject">Reject</option>
                    </select>
                </fieldset>
          </div>
        </div>
    <button class="btn btn-danger" type="submit">Assign Status</button>
    </fieldset>
    </form>
    </div>

</div>

</div>

{% if terror %}
<script>
    alert('Assigned Status successfully');
    window.location = "{% url 'view_doctor' %}";
</script>
{% endif %}

{% endblock %}

HealthDisease/healthapp/templates/contact.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
<div class="map p-2" style="margin-top:6%;border:3px solid lightgray">
		<iframe style="width:100%;height:400px" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3665.782761911858!2d77.46339231490936!3d23.250990984837905!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397c438fbf8a7929%3A0x5e347262325ca71!2sYCT%20Academy!5e0!3m2!1shi!2sin!4v1583523254326!5m2!1shi!2sin"
	allowfullscreen></iframe>

</div>
	<div class="contact-w3l py-5" id="contact">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-sm-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-bl font-weight-bold">Contact Us</h3>
			</div>
			<div class="row pt-md-0">
				<div class="col-lg-6 contact-agileits-w3layouts">
					<h4 class="contact-title text-uppercase text-bl mb-sm-4 mb-3">Our Address</h4>
					<h5 class="font-weight-light text-bl">If you have any questions about the services we provide simply use the
						form below. We try and respond to all queries
						and comments within 24 hours.</h5>
					<div class="midd-contact my-xl-5 my-4 pl-4 border-left">
						<h6 class="text-bl mb-2">Address & Direction:</h6>
						<p>sed quia consequuntur magni dolores eos qui</p>
					</div>
					<p class="para-agileits-w3layouts">
						<i class="fa fa-map-marker pr-3"></i>462022 YCT Academy,Bhopal</p>
					<p class="para-agileits-w3layouts my-sm-3 my-2">
						<i class="fa fa-phone pr-3"></i>0123456789</p>
					<p class="para-agileits-w3layouts">
						<i class="fa fa-envelope-open pr-2"></i>
						<a href="mailto:mail@example.com">info 1@example.com</a>
					</p>
				</div>
				<div class="col-lg-6 regstr-r-w3-agileits mt-lg-0 mt-5">
					<h4 class="contact-title text-uppercase text-bl mb-sm-4 mb-3">Get in Touch</h4>
					<div class="form-bg-w3ls">
						<form action="#" method="post">
							<div class="form-group">
								<input type="text" name="Name" class="form-control" placeholder="Name" required="">
							</div>
							<div class="form-group">
								<input type="email" name="Email" class="form-control" placeholder="Email" required="">
							</div>
							<div class="form-group">
								<input type="text" name="Subject" class="form-control" placeholder="Subject" required="">
							</div>
							<div class="form-group">
								<textarea name="Message" class="form-control" placeholder="Message" required=""></textarea>
							</div>
							<button type="submit" class="button-w3layouts btn btn-primary text-uppercase">Submit</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //contact -->
	<!-- map -->

	<!-- //map -->

{% endblock %}


	<!-- page details -->

HealthDisease/healthapp/templates/donate_blood.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->
{% ifequal error "create" %}
<script>
    alert('Add a new Doctor Successfully');
    window.location="{% url 'view_doctor' %}";
</script>
{% endifequal %}


	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Register for blood Donation</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					
					<div class="form-group row">
						<div class="col-md-6">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username" placeholder="Username" value="{{request.user.username}}" required readonly>
						</div>
						<div class="col-md-6">
                            <label>Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Enter Email" required="" value="{{request.user.email}}" readonly>
                        </div>
					</div>
					
					<div class="form-group row">
						<div class="col-md-6">
                            <label>Blood Group</label>
                            <input type="text" class="form-control" name="bg" placeholder="Enter Blood Group">
						</div>
                        <div class="col-md-6">
                            <label>Place</label>
                            <input type="text" class="form-control" name="place" placeholder="Enter Place" required>
						</div>
					</div>
                    <br>
					<div class="form-group row">
						<div class="col-md-12">
                            <input type="checkbox" name="mycheck" id="mycheck" required>
                            <label class="mb-2">I certify that the information I am about to provided is true and complete to
                                the best of my knowledge. I am aware that this self declaration statement is
                                subject to review and verification and if such information has been falsified I
                                may be terminated from this organisation.</label>
						</div>
					</div>
					
					<button type="submit" class="btn btn-primary submit mt-4">Register</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% for i in messages %}
<script>
  alert("{{i}}")
</script>
{% endfor %}

{% endblock %}

HealthDisease/healthapp/templates/donator_blood.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<style>
  body {font-family: Arial, Helvetica, sans-serif;}
  
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* Modal Content */
  .modal-content {
    position: relative;
    background-color: #fefefe;
    margin: auto;
    margin-top:6%;
    padding: 0;
    border: 1px solid #888;
    width: 60%;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
    -webkit-animation-name: animatetop;
    -webkit-animation-duration: 0.4s;
    animation-name: animatetop;
    animation-duration: 0.4s
  }
  
  /* Add Animation */
  @-webkit-keyframes animatetop {
    from {top:-300px; opacity:0} 
    to {top:0; opacity:1}
  }
  
  @keyframes animatetop {
    from {top:-300px; opacity:0}
    to {top:0; opacity:1}
  }
  
  /* The Close Button */
  .close {
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
  }
  
  .modal-header {
    padding: 4px 16px;
    background-color: #fff;
    
  }
  
  .modal-body {padding: 2px 16px;}
  
  .modal-footer {
    padding: 2px 16px;
    background-color: #fff;
    
  }
  </style>

<div class="container-fluid" style="width:90%;margin-top:10%">
                    <div class="container-fluid">
                      <a href="/donator_blood?action=Pending">
                        <button type="button" class="btn btn-primary pull-left">Pending</button>
                      </a>
                        <h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">
                          
                          {% if request.GET.action %} {{request.GET.action}} {% else %} All{% endif %} Donator for Blood
                          
                      <a href="/donator_blood?action=Approved">    
                        <button type="button" class="btn btn-primary pull-right">Approved</button>
                      </a>
                        </h1>
                        <div id="myModal" class="modal">
                          
                          <!-- Modal content -->
                          <div class="modal-content">
                            <div class="modal-header">
                              <h2>Request for blood</h2>
                              <span class="close">&times;</span>
                              
                            </div>
                            <div class="modal-body">
                              <div class="login px-sm-12" style="width:100%">
                                <form action="{% if doctor %}/change_doctor/{{doctor.id}}/{% else %}/add_doctor{% endif %}" method="post" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  
                                  <div class="form-group row">
                                    <div class="col-md-6">
                                                    <label>Username</label>
                                                    <input type="text" class="form-control" name="username" placeholder="Username" value="{{request.user.username}}" required readonly>
                                    </div>
                                    <div class="col-md-6">
                                                    <label>Email</label>
                                                    <input type="email" class="form-control" name="email" placeholder="Enter Email" required="" value="{{request.user.email}}" readonly>
                                                </div>
                                  </div>
                                  
                                  <div class="form-group row">
                                    <div class="col-md-6">
                                                    <label>Blood Group</label>
                                                    <input type="text" class="form-control" name="bg" placeholder="Enter Blood Group">
                                    </div>
                                                <div class="col-md-6">
                                                    <label>Place</label>
                                                    <input type="text" class="form-control" name="place" placeholder="Enter Place" required>
                                    </div>
                                  </div>
                                            <br>
                                  <div class="form-group row">
                                    <div class="col-md-12">
                                                    <input type="checkbox" name="mycheck" id="mycheck" required>
                                                    <label class="mb-2">I certify that the information I am about to provided is true and complete to
                                                        the best of my knowledge. I am aware that this self declaration statement is
                                                        subject to review and verification and if such information has been falsified I
                                                        may be terminated from this organisation.</label>
                                    </div>
                                  </div>
                                  
                                  <button type="submit" class="btn btn-primary submit mt-4 pull-right">Register</button>
                                </form>
                              </div>
                            </div>
                            
                          </div>
                        
                        </div>
                         </div><hr>
                                <table id="example" class="display" style="width:100%">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>Creation Date</th>
                                      <th>Name</th>
                                      <th>Email</th>
                                      <th>Mobile</th>
                                      <th>Blood Group</th>
                                      <th>Address</th>
                                      <th>Status</th>
                                  </tr>
                              </thead>
                              <tbody>
                              {% for i in data %}
                                <tr>
                                  <td>{{forloop.counter}}</td>
                                  <td>{{i.created}}</td>
                                  <td>{{i.user.user.first_name}} {{i.user.user.last_name}}</td>
                                  <td>{{i.user.user.email}}</td>
                                  <td>{{i.user.contact}}</td>
                                  <td>{{i.blood_group}}</td>
                                  <td>{{i.place}}</td>
                                  <td>
                                    <a href="/change_status/{{i.id}}/?data={{request.get_full_path}}">
                                      <button type="button" class="btn btn-primary">{% if i.status == "Approved" %}Deny{% else %}Approve{% endif %} </button>
                                    </a>
                                  </td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>


<script>
                    // Get the modal
                    var modal = document.getElementById("myModal");
                    
                    // Get the button that opens the modal
                    var btn = document.getElementById("myBtn");
                    
                    // Get the <span> element that closes the modal
                    var span = document.getElementsByClassName("close")[0];
                    
                    // When the user clicks the button, open the modal 
                    btn.onclick = function() {
                      modal.style.display = "block";
                    }
                    
                    // When the user clicks on <span> (x), close the modal
                    span.onclick = function() {
                      modal.style.display = "none";
                    }
                    
                    // When the user clicks anywhere outside of the modal, close it
                    window.onclick = function(event) {
                      if (event.target == modal) {
                        modal.style.display = "none";
                      }
                    }
                    </script>

{% for i in messages %}
<script>
  alert("{{i}}")
</script>
{% endfor %}
{% endblock %}

HealthDisease/healthapp/templates/edit_disease.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->
{% ifequal error "create" %}
<script>
    alert('Disease Updated Successfully');
    window.location="{% url 'view_disease' %}";
</script>
{% endifequal %}


	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Update Disease</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-md-12">
						<label>Disease Name</label>
						<input type="text" class="form-control" value="{{doc.name}}" name="d_name" placeholder="Disease Name" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-12">
						<label>Write Symptom Of Disease (Seperated by ",")</label>
						<textarea class="form-control" name="sym" required="">{{doc.symptom}}
                        </textarea>
                        </div>
					</div>
					<div class="form-group row">
						<div class="col-md-12">
						<label>Type of Disease</label>
						<select class="form-control" name="type" required="">
                        {% for i in type  %}
                            {% ifequal i.name doc.type.name %}
                        <option value="{{i.name}}" selected>{{i.name}}</option>
                            {% else %}
                        <option value="{{i.name}}">{{i.name}}</option>
                            {% endifequal %}
                        {% endfor %}
                        </select>
						</div>
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Register Disease</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% endblock %}

HealthDisease/healthapp/templates/edit_doctor.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
	<!-- register -->
{% ifequal error "create" %}
<script>
    alert('Doctor Updated Successfully');
    window.location="{% url 'view_doctor' %}";
</script>
{% endifequal %}


	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Update Doctor</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-md-6">
						<label>First Name</label>
						<input type="text" class="form-control" value="{{doc.user.first_name}}" name="fname" placeholder="First Name" required="">
						</div>
						<div class="col-md-6">
						<label>Last Name</label>
						<input type="text" class="form-control" value="{{doc.user.last_name}}" name="lname" placeholder="Last Name" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label>Email</label>
						<input type="email" class="form-control" value="{{doc.user.email}}" name="email" placeholder="Enter Email" required="">
						</div>
						<div class="col-md-6">
						<label>Contact</label>
						<input type="text" class="form-control" name="contact" value="{{doc.contact}}" placeholder="Enter Contact" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label>Select Type of category[Current Category : "{{doc.category}}"]</label>
							<select class="form-control" name="type">
								{% for i in type %}
								{% ifequal i.name doc.category %}
								<option value="{{i.name}}" selected>{{i.name}}</option>
								{% else %}
								<option value="{{i.name}}">{{i.name}}</option>
								{% endifequal %}
								{% endfor %}
							</select>
						</div>
						<div class="col-md-6">
						<label>Contact</label>
						<input type="text" class="form-control" name="contact" value="{{doc.contact}}" placeholder="Enter Contact" required="">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-6">
						<label class="mb-2">Address</label>
						<input type="text" class="form-control" value="{{doc.address}}" name="add" id="password1" placeholder="Enter Address" required="">
						</div>
						<div class="col-md-4">
						<label>Image</label>
						<input type="file" class="form-control" name="image">
						</div>
                        <div class="col-md-2">
						<img src="{{doc.image.url}}" style="width:70%;height:200px">
						</div>
					</div>
					<button type="submit" class="btn btn-primary submit mt-4">Update Doctor</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% endblock %}

HealthDisease/healthapp/templates/view_feedback.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<div class="container-fluid" style="width:90%;margin-top:8%">
                    <div class="container-fluid">
                        <h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">View Feedback</h1>
                         </div><hr>
                                <table id="example" class="display" style="width:100%">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>Full Name</th>
                                      <th>Email</th>
                                      <th>Contact</th>
                                      <th>Messages</th>
                                      <th>Action</th>

                                  </tr>
                              </thead>
                              <tbody>
                              {% for i in dis %}
                                <tr>
                                  <td>{{forloop.counter}}</td>
                                  <td>{{i.user.first_name}} {{i.user.user.last_name}}</td>
                                  <td>{{i.user.email}}</td>
                                  <td>{{i.user.patient_set.all.0.contact}}</td>
                                  <td>{{i.messages}}</td>
                                  <td style="width:150px">
                                      <a href="{% url 'delete_feedback' i.id %}" ><button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></button></a></td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>
{% endblock %}